import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AppShell from "@/components/layout/AppShell";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Inline script that runs before paint to prevent flash of incorrect theme.
 * Reads localStorage, falls back to prefers-color-scheme, defaults to dark.
 */
const themeScript = `(function(){try{var s=localStorage.getItem("theme");if(s==="light"||s==="dark"){document.documentElement.setAttribute("data-theme",s);return}if(window.matchMedia("(prefers-color-scheme: light)").matches){document.documentElement.setAttribute("data-theme","light")}}catch(e){}})();`;

/**
 * JSON-LD structured data for SEO.
 * Describes the website as a WebSite and GovernmentService.
 */
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": "https://riksdagsrosten.se/#website",
      url: "https://riksdagsrosten.se",
      name: "Riksdagsrösten",
      description: "Se hur riksdagsledamöterna röstat under mandatperioden 2022–2026",
      inLanguage: "sv-SE",
      potentialAction: {
        "@type": "SearchAction",
        target: "https://riksdagsrosten.se/?q={search_term_string}",
        "query-input": "required name=search_term_string",
      },
    },
    {
      "@type": "Organization",
      "@id": "https://riksdagsrosten.se/#organization",
      name: "Riksdagsrösten",
      url: "https://riksdagsrosten.se",
      logo: {
        "@type": "ImageObject",
        url: "https://riksdagsrosten.se/apple-icon",
      },
    },
  ],
};

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.VERCEL_PROJECT_PRODUCTION_URL
      ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
      : "https://riksdagsrosten.vercel.app"
  ),
  title: {
    default: "Riksdagsrösten – Hur röstade din riksdagsledamot?",
    template: "%s | Riksdagsrösten",
  },
  description:
    "Se hur riksdagsledamöterna röstat under mandatperioden 2022–2026. Sök på ledamot, parti eller ämne.",
  keywords: ["riksdagen", "votering", "riksdagsledamot", "parti", "politik", "sverige", "demokrati"],
  authors: [{ name: "Riksdagsrösten" }],
  manifest: "/manifest.json",
  openGraph: {
    type: "website",
    locale: "sv_SE",
    url: "https://riksdagsrosten.se",
    siteName: "Riksdagsrösten",
    title: "Riksdagsrösten – Hur röstade din riksdagsledamot?",
    description: "Se hur riksdagsledamöterna röstat under mandatperioden 2022–2026. Sök på ledamot, parti eller ämne.",
    // Images are automatically generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Riksdagsrösten – Hur röstade din riksdagsledamot?",
    description: "Se hur riksdagsledamöterna röstat under mandatperioden 2022–2026.",
    // Images are automatically generated by opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
  },
};

/**
 * Root layout for the application.
 * Sets Swedish language, fonts, and wraps all pages in the AppShell.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv" data-theme="dark" className="h-full" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased h-full bg-white dark:bg-zinc-900`}
      >
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
